vim.api.nvim_set_option('number', true)
vim.api.nvim_set_option('ai', true)
vim.api.nvim_set_option('ts', 4)
vim.api.nvim_set_option('sw', 4)
--vim.api.nvim_set_option('sr') 
--vim.api.nvim_set_option('exrc')
vim.api.nvim_set_option('ignorecase', true)
vim.api.nvim_set_option('smartcase', true)
--vim.api.nvim_set_option('nowrap', true)
vim.api.nvim_set_option('termguicolors', true)
vim.api.nvim_set_option('mouse', 'a')
vim.api.nvim_set_option('background', 'light')
vim.api.nvim_set_option('statusline', '+=%F (%l,%c)')

